# Starwars 

::: {.rmdnote}

> **Sample Question:  Which homeworlds have the greatest number of individuals with BMI’s greater than the average for each homework?**

:::

## Data

[Starwars Data](https://github.com/tidyverse/dplyr/tree/main/data-raw)

## Starwars missing values by variable


```{r, echo=FALSE, warning=FALSE, message=FALSE}

library(dplyr)
data("starwars")
q1 <- starwars %>% select(name, height, mass, homeworld, birth_year, species) 
q2 <-  q1 %>%
  summarise_all(funs(sum(is.na(.))))
knitr::kable(q2)
```

### BMI summary

```{r, echo=TRUE, warning=FALSE, message=FALSE}
starwars %>% select(name, height, mass, homeworld) %>% na.omit() %>% 
  mutate(BMI = mass/(height)^2*10000)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
starwars <- starwars %>% select(name, height, mass, homeworld) %>% na.omit() %>% 
  mutate(BMI = mass/(height)^2*10000)
knitr::kable(head(starwars))
```

## BMI summary

```{r, echo=FALSE, warning=FALSE, message=FALSE}
q7 <- starwars %>% summarise(mean_bmi = mean(BMI), median_bmi = median(BMI), max_bmi = max(BMI), min_bmi = min(BMI))
knitr::kable(q7)
```

## Top contenders...

```{r, echo=TRUE, warning=FALSE, message=FALSE}
starwars <- starwars %>%
  group_by(homeworld) %>% 
  mutate(avg_bmi_by_hw = mean(BMI)) %>% 
  ungroup()


above_avg_BMI <- starwars %>%
  filter(BMI > starwars$avg_bmi_by_hw) %>%
  group_by(homeworld) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
short_above <- head(above_avg_BMI, 7)
knitr::kable(short_above)
```

### And the winners are...

```{r, echo=FALSE, warning=FALSE, message=FALSE}
winner <- above_avg_BMI[1:2,]
knitr::kable(winner)
```
